### ISSUE TITLE
Traceback: Failed to establish a new connection: [Errno -2] Name  or service not known

### ISSUE THREAD

**Issue by anandakasula** [alexnest-ua/auto_mhddos_alexnest#6]
Декілька разів вже виникала така проблема під час оновлення списку проксі, без якоїсь періодичності. Запускаю в докер-контейнері, допомагає перезапуск контейнера. Це проблема локальної конфігурації? Покищо наново виконав налаштування по інструкції з https://hub.docker.com/r/alexnestua/auto_mhddos , подивлюсь чи щось зміниться.

```
[07:43:18 - INFO] Новий цикл через: 2 секунд
[07:43:18 - INFO] Кількість проксі: 199
[07:43:20 - INFO] Увага, оновлення! Можливе зниження трафіку, в обмін на збільшення загальної кількості IP, що атак
ують
[07:43:20 - INFO] Завантажуємо список проксі...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7ab0249300>: Failed to est
ablish a new connection: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exce
eded with url: /porthole-ascend-cinnamon/proxy_scraper/main/working_proxies.txt (Caused by NewConnectionError('<url
lib3.connection.HTTPSConnection object at 0x7f7ab0249300>: Failed to establish a new connection: [Errno -2] Name or
 service not known'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/mhddos_proxy/runner.py", line 182, in <module>
    start(init_argparse().parse_args())
  File "/root/mhddos_proxy/runner.py", line 163, in start
    proxies = update_proxies(args.proxies)
  File "/root/mhddos_proxy/src/proxies.py", line 32, in update_proxies
    raw = requests.get(PROXIES_URL, timeout=20).text
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries e
xceeded with url: /porthole-ascend-cinnamon/proxy_scraper/main/working_proxies.txt (Caused by NewConnectionError('<
urllib3.connection.HTTPSConnection object at 0x7f7ab0249300>: Failed to establish a new connection: [Errno -2] Name
 or service not known'))
```

**Comment by alexnest-ua** [comment]
Версія https://hub.docker.com/r/alexnestua/auto_mhddos не актуальна, вам треба сюди:
https://github.com/alexnest-ua/auto_mhddos_alexnest/tree/docker
